"""added Planet model

Revision ID: 04a524081e25
Revises: 
Create Date: 2022-10-27 19:58:44.752649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a524081e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surface_area', sa.BigInteger(), nullable=True),
    sa.Column('moons', sa.Integer(), nullable=True),
    sa.Column('distance_from_sun', sa.BigInteger(), nullable=True),
    sa.Column('namesake', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('surface_area', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('moons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_from_sun', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('namesake', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planets_pkey')
    )
    op.drop_table('planet')
    # ### end Alembic commands ###
