"""edited Planet

Revision ID: 09ab31844884
Revises: 8a58a107d46c
Create Date: 2022-10-28 18:48:17.947211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ab31844884'
down_revision = '8a58a107d46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('planet', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'name')
    # ### end Alembic commands ###
