"""removed flag

Revision ID: 5b317c8c141e
Revises: dc8232bcbf6e
Create Date: 2022-10-31 16:20:55.928060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b317c8c141e'
down_revision = 'dc8232bcbf6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
