"""add is_dwarf attribute

Revision ID: 65348fa233e7
Revises: 036c26fe57f3
Create Date: 2022-11-01 10:54:27.577573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65348fa233e7'
down_revision = '036c26fe57f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('is_dwarf', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'is_dwarf')
    # ### end Alembic commands ###
