"""Edit: change title to name

Revision ID: 6d23af56ab38
Revises: ab6ca08cc892
Create Date: 2022-11-01 08:06:50.965848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d23af56ab38'
down_revision = 'ab6ca08cc892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('planet', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'name')
    # ### end Alembic commands ###
