"""added fictional caretaker

Revision ID: b3e2f14f62df
Revises: ba34c22df00a
Create Date: 2022-11-04 13:01:29.400980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e2f14f62df'
down_revision = 'ba34c22df00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caretaker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('planet', sa.Column('caretaker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'caretaker', ['caretaker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'caretaker_id')
    op.drop_table('caretaker')
    # ### end Alembic commands ###
