"""re-added flag

Revision ID: eaeb0e236b3c
Revises: 5b317c8c141e
Create Date: 2022-10-31 16:30:08.673148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaeb0e236b3c'
down_revision = '5b317c8c141e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'flag')
    # ### end Alembic commands ###
