"""adds Planet model

Revision ID: fcd7941f9078
Revises: 
Create Date: 2022-10-28 11:13:46.482505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd7941f9078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('moon_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('surface_area', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moons', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distance_from_sun', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('namesake', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='planets_pkey')
    )
    op.drop_table('planet')
    # ### end Alembic commands ###
